### ISSUE TITLE
npm install failed.

### ISSUE THREAD

**Issue by hjianhao** [uber/hyperbahn#287]
I run the command npm install, got the following errors : 

> farmhash@0.2.2 install /home/hjianhao/nodeprj/hyperbahn/node_modules/farmhash
> node-gyp rebuild

make: Entering directory '/home/hjianhao/nodeprj/hyperbahn/node_modules/farmhash/build'
  CXX(target) Release/obj.target/farmhash/src/upstream/farmhash.o
  CXX(target) Release/obj.target/farmhash/src/bindings.o
In file included from ../../nan/nan_new.h:190:0,
                 from ../../nan/nan.h:74,
                 from ../src/bindings.cc:4:
../../nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../../nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../../nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from /home/hjianhao/.node-gyp/6.0.0/include/node/node.h:42:0,
                 from ../src/bindings.cc:2:
/home/hjianhao/.node-gyp/6.0.0/include/node/v8.h:4798:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/hjianhao/.node-gyp/6.0.0/include/node/v8.h:4798:27: note:   candidate expects 2 arguments, 4 provided
In file included from ../src/bindings.cc:4:0:
../../nan/nan.h: At global scope:
../../nan/nan.h:165:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../../nan/nan.h:160:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../../nan/nan.h:369:20: error: variable or field ‘NanAddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:369:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’

                    ^
../../nan/nan.h:369:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’

my node.js and npm version as following. 

npm ERR! Linux 3.19.0-16-generic
npm ERR! argv "/home/hjianhao/dev/node-v6.0.0-linux-x64/bin/node" "/home/hjianhao/dev/node/bin/npm" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

**Comment by hjianhao** [comment]
My OS : Ubuntu 15.04

**Comment by Raynos** [comment]
Hyperbahn is not node6 compliant yet. It should work on node0.10 or node4
